env:
  node: true
  commonjs: true
  browser: true
  es6: true
  jest/globals: true
extends:
  - 'eslint:recommended'
plugins:
  - jest
parser: babel-eslint
parserOptions:
  ecmaVersion: 2016
  sourceType: module
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  strict: error
  eol-last: error
