version: '3'
services:

  app:
    build: .
    ports:
      - 80:80
    volumes:
      - '/var/www'
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
