defaults: &defaults
  working_directory: /opt/app

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: node:12.8.1-alpine
    steps:
      - checkout
      - run:
          name: Enable apk cache
          command: setup-apkcache
      - restore_cache:
          keys:
            - apk-cache-{{ checksum "date" }}
#            - npm-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: apk-cache-{{ checksum "date" }}
          paths:
            - /etc/apk/cache
#      - save_cache:
#          key: npm-cache-{{ checksum "package-lock.json" }}
#          paths:
#            - ~/.npm/
#      - run:
#          name: Install OS dependencies
#          command: apk add git
      - run:
          name: Install node dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
