version: 2
jobs:
  build:
    working_directory: /opt/app
    docker:
      - image: node:10.16.3-alpine
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: |
            apk add --no-cache --no-progress \
              ca-certificates \
              build-base \
              autoconf \
              automake \
              zlib \
              bash \
              libltdl \
              libtool \
              zlib-dev \
              nasm
            export ACLOCAL_PATH=/usr/share/aclocal
            export LIBRARY_PATH=/lib:/usr/lib
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
