defaults: &defaults
  working_directory: /opt/app

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: node:12.8.1-alpine
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: |
            apk add --no-cache --no-progress \
              ca-certificates
      - restore_cache:
          keys:
            - npm-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build
          command: npm run build
